#!/bin/sh

# Read input from stdin
while read oldrev newrev refname; do
  if [[ $refname =~ ^refs/tags/ ]]; then
    tag=${refname#refs/tags/}
    if [[ ! $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ && ! $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
      echo "Tag $tag does not match the required format x.y.z or x.y.z-rc.w"
      exit 1
    fi
  fi
done

exit 0